#
# @@-COPYRIGHT-START-@@
#
# Copyright (c) 2014 Qualcomm Atheros, Inc.
# All rights reserved.
# Qualcomm Atheros Confidential and Proprietary.
#
# @@-COPYRIGHT-END-@@
#

include ../../build/config.mk
include ../../build/module.mk
