#!/bin/sh
uci -q batch <<-EOF
    delete ucitrack.@omr-tracker[-1]
    add ucitrack omr-tracker
    set ucitrack.@omr-tracker[-1].init="omr-tracker"
    commit ucitrack
EOF
if [ "$(uci -q ucitrack.@network[-1].affects | grep omr-tracker)" = "" ]; then
	uci -q batch <<-EOF
	    add_list ucitrack.@network[-1].affects="omr-tracker"
	    commit ucitrack
	EOF
fi
if [ "$(uci -q ucitrack.@shadowsocks-libev[-1].affects | grep omr-tracker)" = "" ]; then
	uci -q batch <<-EOF
	    add_list ucitrack.@shadowsocks-libev[-1].affects="omr-tracker"
	    commit ucitrack
	EOF
fi

uci -q set openmptcprouter.vps=vps