#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@omr-tracker[-1]
	add ucitrack omr-tracker
	set ucitrack.@omr-tracker[-1].init="omr-tracker"
	commit ucitrack
EOF
if [ "$(uci -q get ucitrack.@network[-1].affects | grep omr-tracker)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		add_list ucitrack.@network[-1].affects="omr-tracker"
		commit ucitrack
	EOF
fi
if [ "$(uci -q get ucitrack.@shadowsocks-libev[-1].affects | grep omr-tracker)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		add_list ucitrack.@shadowsocks-libev[-1].affects="omr-tracker"
		commit ucitrack
	EOF
fi
if [ "$(uci -q get omr-tracker.defaults.interval_tries)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		set omr-tracker.defaults.interval_tries=1
		commit omr-tracker
	EOF
fi
if [ "$(uci -q get omr-tracker.shadowsocks.hosts | grep '23.96.52.53')" != "" ]; then
	uci -q batch <<-EOF >/dev/null
		del_list omr-tracker.shadowsocks.hosts='23.96.52.53'
		del_list omr-tracker.shadowsocks.hosts='104.40.211.35'
		del_list omr-tracker.shadowsocks.hosts='80.67.169.12'
		add_list omr-tracker.shadowsocks.hosts='104.16.1.1'
		add_list omr-tracker.shadowsocks.hosts='103.224.182.242'
		add_list omr-tracker.shadowsocks.hosts='198.27.92.1'
		add_list omr-tracker.shadowsocks.hosts='88.191.250.176'
		add_list omr-tracker.shadowsocks.hosts='151.101.129.164'
	EOF
fi
exit 0