#!/bin/sh /etc/rc.common

START=11

USE_PROCD=1
NAME=syslogd
PROG=/sbin/syslogd

start_service() {
	local log_size=$(uci -q get system.@system[0].log_size)
	local log_ip=$(uci -q get system.@system[0].log_ip)
	local log_port=$(uci -q get system.@system[0].log_port || echo '514')
	local log_file=$(uci -q get system.@system[0].log_file)
	local conloglevel=$(uci -q get system.@system[0].conloglevel)

	procd_open_instance
	procd_set_param command "$PROG" -n ${log_size:+-C"$log_size"} ${log_ip:+-R"$log_ip":"$log_port"} ${log_file:+-O "$log_file"} ${conloglevel:+-l "$conloglevel"}
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	procd_send_signal syslogd
}

service_data() {
	return 0
}