#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Copyright (C) 2017-2019 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#
# This is based on OpenVPN LuCI Support.
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Glorytun
LUCI_DEPENDS:=+glorytun +glorytun-udp
LUCI_PKGARCH:=all
PKG_LICENSE:=GPLv2

PKG_MAINTAINER:=Ycarus (Yannick Chabanois) <ycarus@zugaina.org>

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
