#!/bin/sh

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" ] && exit 0
[ "$INTERFACE" = "omrvpn" ] || exit 0

/etc/init.d/openmptcprouter-vps set_vpn_ip