#!/bin/sh 

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@omr-tracker[-1]
	add ucitrack omr-tracker
	set ucitrack.@omr-tracker[-1].init=omr-tracker
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
