#!/bin/sh /etc/rc.common

START=5

USE_PROCD=1

start_service() {
	local scaling_min_freq scaling_max_freq
	config_load openmptcprouter
	config_get scaling_min_freq settings scaling_min_freq
	[ -n "$scaling_min_freq" ] && {
		for c in $(ls -d /sys/devices/system/cpu/cpufreq/policy[0-9]*); do
			echo $scaling_min_freq > $c/scaling_min_freq
		done
	}
	config_get scaling_max_freq settings scaling_max_freq
	[ -n "$scaling_max_freq" ] && {
		for c in $(ls -d /sys/devices/system/cpu/cpufreq/policy[0-9]*); do
			echo $scaling_max_freq > $c/scaling_max_freq
		done
	}
	config_get scaling_governor settings scaling_governor
	[ -n "$scaling_governor" ] && {
		for c in $(ls -d /sys/devices/system/cpu/cpufreq/policy[0-9]*); do
			echo $scaling_governor > $c/scaling_governor
		done
	}
	# remove sysctl already defined in /etc/sysctl.d/
	sed -i -e '/tcp_fin_timeout/d' -e '/tcp_keepalive_time/d' -e '/nf_conntrack_max/d' /etc/sysctl.conf
	sed -i -e '/tcp_fin_timeout/d' -e '/tcp_keepalive_time/d' -e '/nf_conntrack_max/d' /etc/sysctl.d/10-default.conf
}

reload_service() {
	rc_procd start_service
	return 0
}