#!/bin/sh

. /lib/functions.sh

if [ "$(uci -q show network | grep omr6in4)" = "" ]; then
	uci -q batch <<-EOF
	set network.omr6in4=interface
	set network.omr6in4.proto=6in4
	set network.omr6in4.ip4table=vpn
	set network.omr6in4.multipath=off
	set network.omr6in4.ipaddr=10.0.0.2
	set network.omr6in4.peeraddr=10.0.0.1
	set network.omr6in4.gateway=fe80::a00:1
	commit network
	add_list firewall.@zone[2].network=omr6in4
	commit firewall
	EOF
	rm -f /tmp/luci-indexcache
fi
exit 0
