#
# Copyright (C) 2018 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Mail Configuration
LUCI_DEPENDS:=+msmtp-mta +ca-certificates

PKG_LICENSE:=GPLv3

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
