#!/bin/sh
uci -q batch <<-EOF
    delete ucitrack.@openmptcprouter[-1]
    add ucitrack openmptcprouter
    set ucitrack.@openmptcprouter[-1].init=openmptcprouter
    commit ucitrack
EOF
if [ "$(uci -q get qos.serverin)" = "" ]; then
	uci -q batch <<-EOF
		set qos.serverin=classify
		set qos.serverin.target='Priority'
		set qos.serverout=classify
		set qos.serverout.target='Priority'
		commit qos
	EOF
fi
if [ "$(uci -q get qos.serverin.target)" = "" ]; then
	uci -q batch <<-EOF
		set qos.serverin.target='Priority'
		set qos.serverout.target='Priority'
		commit qos
	EOF
fi
if [ "$(uci -q ucitrack.@network[-1].affects | grep openmptcprouter)" = "" ]; then
    uci -q batch <<-EOF
        add_list ucitrack.@network[-1].affects="openmptcprouter"
        commit ucitrack
    EOF
fi