#!/bin/sh
uci -q batch <<-EOF
    delete ucitrack.@openmptcprouter[-1]
    add ucitrack openmptcprouter
    set ucitrack.@openmptcprouter[-1].init=openmptcprouter
    commit ucitrack
    delete openmptcprouter.settings
    set openmptcprouter.settings=openmptcprouter
    commit openmptcprouter
EOF