#!/bin/sh
uci -q batch <<-EOF
    delete ucitrack.@macvlan[-1]
    add ucitrack macvlan
    set ucitrack.@macvlan[-1].init=macvlan
    commit ucitrack
EOF
if [ "$(uci -q get ucitrack.@network[-1].affects | grep macvlan)" = "" ]; then
	uci -q batch <<-EOF
		add_list ucitrack.@network[-1].affects=macvlan
		commit ucitrack
	EOF
fi
exit 0