#!/bin/sh
uci -q batch <<-EOF
    delete ucitrack.@macvlan[-1]
    add ucitrack macvlan
    set ucitrack.@macvlan[-1].init=macvlan
    add_list ucitrack.@network[-1].affects=macvlan
    commit ucitrack
EOF