#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@omr-bypass[-1]
	add ucitrack omr-bypass
	set ucitrack.@omr-bypass[-1].init=omr-bypass
	commit ucitrack
EOF

if [ "$(uci -q get omr-bypass.dpi)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		set omr-bypass.dpi=bypass
	EOF
fi

if [ "$(uci -q get ucitrack.@shadowsocks-libev[-1].affects)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		set ucitrack.@shadowsocks-libev[-1].affects=omr-bypass
	EOF
fi
rm -f /tmp/luci-indexcache
exit 0
