#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@omr-bypass[-1]
	add ucitrack omr-bypass
	set ucitrack.@omr-bypass[-1].init=omr-bypass
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
