#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/functions.sh

multipath=
mptcp_path_manager=
mptcp_schdeduler=
congestion=
multipath_status=0
config_load network
config_get multipath globals multipath
config_get mptcp_path_manager globals mptcp_path_manager
config_get mptcp_scheduler globals mptcp_scheduler
config_get congestion globals congestion
[ "$multipath" = "enable" ] && multipath_status=1

# Global MPTCP configuration
sysctl -qw net.mptcp.mptcp_enabled="$multipath_status"
[ "$multipath_status" = "0" ] && exit 0
[ -z "$mptcp_path_manager" ] || sysctl -qw net.mptcp.mptcp_path_manager="$mptcp_path_manager"
[ -z "$mptcp_scheduler" ] || sysctl -qw net.mptcp.mptcp_scheduler="$mptcp_scheduler"
[ -z "$congestion" ] || sysctl -qw net.ipv4.tcp_congestion_control="$congestion"

# Configuration by interface
_setup_interface() {
	device=
	config_get device "$1" ifname
	[ -z "$device" ] && return 0
	[ -n "$(config | grep $device)" ] || return 0
	if_multipath=
	config_get if_multipath "$1" multipath "off"
	[ "$if_multipath" = "master" ] && if_multipath="on"
	multipath "$device" "$if_multipath"
}
config_foreach _setup_interface interface
