#!/bin/sh
#
# Load the multipath config
#
# Author: Mario Krueger <openwrt at xedp3x.de>
# Released under GPL 3 or later

enable=`uci -q get network.globals.multipath` || exit 0
[ "$enable" = "enable" ] || exit 0

. /lib/functions.sh
. /lib/functions/network.sh

id=0
count=1

set_default() {
    local mode
    local config="$1"
    count=$(($count+1))
    local iface
    config_get iface "$config" ifname
    id=$count
    config_get mode "$config" multipath

    mode=`uci -q get network.$config.multipath` || mode='off'
    [ -n "$(ifconfig | grep $iface)" ] || return 1
    case "$mode" in
	"off")
	    multipath $iface off
	    return 1;;
	"master")
	    mode="on";;
	"on");;
	"backup");;
	"handover");;
	*)
	    logger -t multipath Wrong multipath value for device $iface
	    return 1;;
    esac
    # Update kernel flags
    multipath $iface $mode
    # IPv4 Updates:
    local ipaddr
    local gateway
    local network
    local netmask
    config_get ipaddr $config ipaddr
    config_get gateway $config gateway
    network_get_subnet  network $config
    config_get netmask $config netmask
    network=`ipcalc.sh $network | sed -n '/NETWORK=/{;s/.*=//;s/ .*//;p;}'`

    [ -n "$gateway" ] || return 1
    
    ip rule del table $id
    ip route flush $id
    ip rule add from $ipaddr table $id
    ip route replace $network/$netmask dev $iface scope link table $id
    ip route replace default via $gateway dev $iface table $id
    ip route flush $id

    [ "$mode" = "master" ] && {
	ip route replace default via $gateway dev $iface
    }
}

config_load network
config_foreach set_default interface
