#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Copyright (C) 2017 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Administration - full-featured for full control
LUCI_DEPENDS:=+luci-base +luci-app-firewall

PKG_BUILD_DEPENDS:=iwinfo
PKG_LICENSE:=Apache-2.0

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

