#!/bin/sh /etc/rc.common
# Copyright (C) 2018-2026 Ycarus (Yannick Chabanois) <ycarus@zugaina.org> for OpenMPTCProuter
# SPDX-License-Identifier: GPL-3.0

# shellcheck disable=SC2034
START=91
USE_PROCD=1

start_service() {
	local enabled interval

	enabled=$(uci -q get omr-metrics.settings.send_to_vps)
	[ "$enabled" = "0" ] && return

	interval=$(uci -q get omr-metrics.settings.interval)

	procd_open_instance
	procd_set_param command /usr/bin/omr-metrics-send
	[ -n "$interval" ] && procd_append_param env "OMR_METRICS_INTERVAL=$interval"
	procd_set_param respawn 0 10 0
	procd_set_param stderr 1
	procd_close_instance

	local weight_sync_enabled
	weight_sync_enabled=$(uci -q get omr-metrics.settings.enable_weight_sync)
	[ "${weight_sync_enabled:-1}" != "0" ] && {
		procd_open_instance weight_sync
		procd_set_param command /usr/bin/omr-weight-sync
		procd_set_param respawn 0 10 0
		procd_set_param stderr 1
		procd_close_instance
	}
}

service_triggers() {
	procd_add_reload_trigger omr-metrics
}

reload_service() {
	stop
	start
}
