#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.

START=98

start_diag_app()
{
	local serverip=`grep -oh "serverip.*#"  /proc/cmdline  | awk -F '#' '{print $2}'`
	/usr/sbin/diag_socket_app -a $serverip &
	echo "/usr/sbin/diag_socket_app started" > /dev/kmsg
}

start() {
	is_ftm=`grep wifi_ftm_mode /proc/cmdline | wc -l`
	[ $is_ftm = 1 ] && start_diag_app
}

