#!/bin/sh
#
# Copyright (c) 2020 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

[ "${ACTION}" = "add" ] && {

	[ -e /tmp/.wifi-config-done ] && {
		return
	}

	/sbin/wifi config > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		cat /tmp/wireless.tmp >> /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	touch /tmp/.wifi-config-done
}

