#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=9
STOP=98

boot() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -n "$files" ] && {
		mkdir /usr/share/omr-update
		cp /etc/uci-defaults/* /usr/share/omr-update
		return 0
	}

	cd /usr/share/omr-update || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	for file in $files; do
		( . "./$(basename $file)" )
	done
	uci commit

	# temporary hack until configd exists
	/sbin/reload_config
}
