#!/bin/sh /etc/rc.common

START=99
start()
{
tem=$(cat /sys/class/thermal/thermal_zone0/temp)
echo $tem
if [ $tem -ge 60000 ] ; then # 温度高于 60 风扇开始转，可修改，正常使用设置为55000
echo 1 > /sys/class/leds/green:fengshan/brightness;
elif [ $tem -le 50000 ] ; then # 温度低于 50 速度降低，可修改
echo 0 > /sys/class/leds/green:fengshan/brightness;
echo "temdown"
fi #多加了fi
}