#!/bin/sh /etc/rc.common

START=20
start()
{
tem=$(cat /sys/class/thermal/thermal_zone0/temp)
echo $tem
if [ $tem -ge 60000 ]
then
echo 1 > /sys/class/leds/green:fengshan/brightness
fi
if [ $tem -le 50000 ]
then
echo 0 > /sys/class/leds/green:fengshan/brightness
#echo 14 >/sys/class/gpio/unexport
echo "temdown"
fi
}