#!/bin/sh /etc/rc.common

START=20
start()
{
logger "setting usbnetwork_power"
/bin/sleep 3
/sbin/usbmode -l 2>&1 /dev/null
/bin/sleep 3
/sbin/usbmode -s 2>&1 /dev/null
/bin/sleep 3
echo "0" > "/sys/class/leds/green:5g1pwr/brightness"
logger "5g1pwr 0"
/bin/sleep 2
echo "0" > "/sys/class/leds/green:5g2pwr/brightness"
logger "5g2pwr 0"
/bin/sleep 2
echo "0" > "/sys/class/leds/green:5g3pwr/brightness"
logger "5g3pwr 0"
/bin/sleep 2
echo "1" > "/sys/class/leds/green:5g1pwr/brightness"
logger "5g1pwr 1"
/bin/sleep 2
echo "1" > "/sys/class/leds/green:5g2pwr/brightness"
logger "5g2pwr 1"
/bin/sleep 2
echo "1" > "/sys/class/leds/green:5g3pwr/brightness"
logger "5g3pwr 1"
}