#!/bin/sh
[ "$OMR_TRACKER_STATUS" = "OK" ] || exit 0
[ -z "$OMR_TRACKER_SERVER_IP" ] && exit 0
# The iperf section of a server is named after it (openmptcprouter-vps)
[ -z "$OMR_TRACKER_SERVER_NAME" ] && exit 0

ip="$OMR_TRACKER_SERVER_IP"
host="$(uci -q get iperf.$OMR_TRACKER_SERVER_NAME.host)" || exit 0
[ "$host" != "$ip" ] && uci -q set iperf.$OMR_TRACKER_SERVER_NAME.host="$ip" && uci -q commit iperf
