#!/bin/sh
[ "$OMR_TRACKER_STATUS" = "OK" ] || exit 0
[ -z "$OMR_TRACKER_SERVER_IP" ] && exit 0

ip="$OMR_TRACKER_SERVER_IP"
[ "$(uci -q get iperf.vps.host)" != "$ip" ] && uci -q set iperf.vps.host="$ip" && uci -q commit iperf