#!/bin/sh
if [ "$(uci -q get snmpd.general.network)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		add_list snmpd.general.network=lan
		set snmpd.@system[0].sysName="OpenMPTCProuter"
		set snmpd.general.enabled=0
		commit snmpd
	EOF
fi
exit 0