#
# Copyright (C) 2018 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for MLVPN
LUCI_DEPENDS:=+mlvpn

PKG_LICENSE:=GPLv3

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
