#
# Copyright (C) 2018 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for omr-tracker
LUCI_DEPENDS:=+omr-tracker

PKG_LICENSE:=Apache-2.0

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
