#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=58
USE_PROCD=1

log() {
	logger -t "z8102" "$@"
}

start_service()
{
	i=459
	echo $i > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio${i}/direction
	echo "1" > /sys/class/gpio/gpio${i}/value
	i=460
	echo $i > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio${i}/direction
	echo "1" > /sys/class/gpio/gpio${i}/value
	i=461
	echo $i > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio${i}/direction
	echo "0" > /sys/class/gpio/gpio${i}/value
	i=462
	echo $i > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio${i}/direction
	echo "0" > /sys/class/gpio/gpio${i}/value
	/usr/lib/custom/wdg.sh &
}
