#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@glorytun[-1]
	add ucitrack glorytun
	set ucitrack.@glorytun[-1].init=glorytun
	delete ucitrack.@glorytun-udp[-1]
	add ucitrack glorytun-udp
	set ucitrack.@glorytun-udp[-1].init=glorytun-udp
	commit ucitrack
EOF

uci -q batch <<-EOF >/dev/null
	delete network.glorytun=interface
	set network.glorytun=interface
	set network.glorytun.ifname=tun0
	set network.glorytun.proto=none
	set network.glorytun.ip4table=vpn
	set network.glorytun.multipath=off
	set network.glorytun.defaultroute=0
	commit network
EOF
uci -q batch <<-EOF >/dev/null
	add firewall zone
	set firewall.@zone[-1].name=vpn
	set firewall.@zone[-1].network='vpn'
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
