#
# Copyright (C) 2018 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI SNMPD Interface
LUCI_DEPENDS:=+snmpd

PKG_LICENSE:=GPLv3

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
