#!/bin/sh

if [ "$(uci -q get dscp)" = "" ]; then
	uci -q batch <<-EOF
		add dscp classify
		set dscp.@classify[0].direction='both'
		set dscp.@classify[0].proto='icmp'
		set dscp.@classify[0].class='cs5'
		set dscp.@classify[0].comment='ICMP'
		set dscp.@classify[1].direction='both'
		set dscp.@classify[1].proto='udp'
		set dscp.@classify[1].class='cs5'
		set dscp.@classify[1].src_port='53,123,5353'
		set dscp.@classify[1].comment='DNS udp and NTP'
		set dscp.@classify[2].direction='both'
		set dscp.@classify[2].proto='tcp'
		set dscp.@classify[2].class='cs5'
		set dscp.@classify[2].src_port='53,5353'
		set dscp.@classify[2].comment='DNS tcp'
		commit dscp
	EOF
fi

exit 0