#!/bin/sh

cd /etc/uci-defaults || exit 0
# Keep dnsmasq ipset with old method
rm -f /etc/uci-defaults/50-dnsmasq-migrate-ipset.sh

source /etc/os-release

files="$(ls /etc/uci-defaults/)"
[ -n "$files" ] && {
	mkdir -p /usr/share/omr-update
	if [ "$(grep rom /etc/mtab)" = "" ]; then
		rm /usr/share/omr-update/*
		cp /etc/uci-defaults/* /usr/share/omr-update
	fi
}
exit 0
