#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set luci.diag=external
	set luci.diag.ping="openmptcprouter.com"
	set luci.diag.dns="openmptcprouter.com"
	set luci.diag.route="openmptcprouter.com"
	commit luci
EOF
rm -f /tmp/luci-indexcache

exit 0
