#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete qos.wan
	set qos.wan1=interface
	set qos.wan1.classgroup="Default"
	set qos.wan1.enabled="0"
	set qos.wan1.upload="128"
	set qos.wan1.download="1024"
	set qos.wan2=interface
	set qos.wan2.classgroup="Default"
	set qos.wan2.enabled="0"
	set qos.wan2.upload="128"
	set qos.wan2.download="1024"
	commit qos
EOF
rm -f /tmp/luci-indexcache

exit 0
