#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete vnstat.@vnstat[-1]
	add vnstat vnstat
	set vnstat.@vnstat[-1].interface="wan1"
	add_list vnstat.@vnstat[-1].interface="wan2"
	commit vnstat
EOF
rm -f /tmp/luci-indexcache

exit 0
