#!/bin/sh

uci -q batch <<-EOF >/dev/null
	add firewall rule
	firewall.@rule[-1].enabled='1'
	firewall.@rule[-1].target='ACCEPT'
	firewall.@rule[-1].name='Allow-All-Ping'
	firewall.@rule[-1].proto='icmp'
	firewall.@rule[-1].dest='*'
	firewall.@rule[-1].src='*'
	firewall.@rule[-1].icmp_type='echo-request'
	commit firewall
EOF
rm -f /tmp/luci-indexcache

exit 0
