#!/bin/sh

if [ "$(uci -q get omr-tracker.tun0)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		set omr-tracker.tun0=interface
		set omr-tracker.tun0.type="none"
		set omr-tracker.tun0.timeout=1
		set omr-tracker.tun0.tries=4
		set omr-tracker.tun0.interval=2
		commit omr-tracker
	EOF
fi
rm -f /tmp/luci-indexcache

exit 0
