#!/bin/sh

uci -q show system.@rngd[0] || {
        uci add system rngd
        uci set system.@rngd[0].device=/dev/urandom
        uci commit
}

uci -q batch <<-EOF >/dev/null
	set system.@rngd[0].enabled=1
	commit system
EOF

exit 0
