#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mptcpovervpn[-1]
	add ucitrack mptcpovervpn
	set ucitrack.@mptcpovervpn[-1].init="mptcpovervpn"
	commit ucitrack
EOF
if [ "$(uci -q get ucitrack.@network[-1].affects | grep mptcpovervpn)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		add_list ucitrack.@network[-1].affects="mptcpovervpn"
		commit ucitrack
	EOF
fi
exit 0