#!/bin/sh

if [ "$(uci -q get openmptcprouter.latest_versions)" = "" ]; then
	uci -q show wireless.default_radio0 && {
		uci -q batch <<-EOF >/dev/null
			delete wireless.default_radio0
			commit wireless
		EOF
	}
fi

exit 0