#!/bin/sh
if [ "$(uci -q get openmptcprouter.latest_versions)" = "" ]; then
	if [ "$(uci -q get sqm.wan1)" = "" ]; then
		wan1="$(uci -q get network.wan1.ifname)"
		wan2="$(uci -q get network.wan2.ifname)"
		uci -q batch <<-EOF >/dev/null
			delete sqm.eth1
			set sqm.wan1=queue
			set sqm.wan1.qdisc="fq_codel"
			set sqm.wan1.script="simple.qos"
			set sqm.wan1.qdisc_advanced='0'
			set sqm.wan1.linklayer='none'
			set sqm.wan1.enabled='0'
			set sqm.wan1.interface=$wan1
			set sqm.wan1.download='0'
			set sqm.wan1.upload='0'
			set sqm.wan1.debug_logging='0'
			set sqm.wan1.verbosity='5'
			set sqm.wan2=queue
			set sqm.wan2.qdisc="fq_codel"
			set sqm.wan2.script="simple.qos"
			set sqm.wan2.qdisc_advanced='0'
			set sqm.wan2.linklayer='none'
			set sqm.wan2.enabled='0'
			set sqm.wan2.interface=$wan2
			set sqm.wan2.download='0'
			set sqm.wan2.upload='0'
			set sqm.wan2.debug_logging='0'
			set sqm.wan2.verbosity='5'
			commit sqm
		EOF
		if [ "$(uci -q get network.wan3)" != "" ]; then
			wan3="$(uci -q get network.wan3.ifname)"
			uci -q batch <<-EOF >/dev/null
				set sqm.wan3=queue
				set sqm.wan3.qdisc="fq_codel"
				set sqm.wan3.script="simple.qos"
				set sqm.wan3.qdisc_advanced='0'
				set sqm.wan3.linklayer='none'
				set sqm.wan3.enabled='0'
				set sqm.wan3.interface=$wan3
				set sqm.wan3.download='0'
				set sqm.wan3.upload='0'
				set sqm.wan3.debug_logging='0'
				set sqm.wan3.verbosity='5'
				commit sqm
			EOF
		fi
		if [ "$(uci -q get network.wan4)" != "" ]; then
			wan4="$(uci -q get network.wan4.ifname)"
			uci -q batch <<-EOF >/dev/null
				set sqm.wan4=queue
				set sqm.wan4.qdisc="fq_codel"
				set sqm.wan4.script="simple.qos"
				set sqm.wan4.qdisc_advanced='0'
				set sqm.wan4.linklayer='none'
				set sqm.wan4.enabled='0'
				set sqm.wan4.interface=$wan4
				set sqm.wan4.download='0'
				set sqm.wan4.upload='0'
				set sqm.wan4.debug_logging='0'
				set sqm.wan4.verbosity='5'
				commit sqm
			EOF
		fi
	fi
fi
rm -f /tmp/luci-indexcache

exit 0
