#!/bin/sh
if [ "$(uci -q get openmptcprouter.settings.version)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		set uhttpd.main.redirect_https=0
		set uhttpd.main.script_timeout=240
		set uhttpd.main.network_timeout=240
		set uhttpd.main.http_keepalive=0
	EOF
fi
exit 0