#!/bin/sh
uci -q batch <<-EOF >/dev/null
	set system.@system[-1].ttylogin=1
	set system.ntp.use_dhcp='0'
	set system.ntp.enable_server='1'
	commit system
	set rpcd.@rpcd[0].timeout=120
	commit rpcd
EOF
exit 0