#!/bin/sh
if [ "$(uci -q get firewall.omr-server)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		set firewall.omr-server=include
		set firewall.omr-server.path=/etc/firewall.omr-server
		commit firewall
	EOF
fi

exit 0
