#!/bin/sh

if [ "$(grep usbmode /etc/rc.local)" = "" ]; then
	sed -i 's:exit 0::g' /etc/rc.local
	cat <<-EOF >> /etc/rc.local
		/bin/sleep 5
		/sbin/usbmode -l 2>&1 /dev/null
		/bin/sleep 3
		/sbin/usbmode -s 2>&1 /dev/null
		/bin/sleep 10
echo 0 >/sys/class/leds/green:5g1pwr/brightness
/bin/sleep 2
echo 0 >/sys/class/leds/green:5g2pwr/brightness
/bin/sleep 2
echo 0 >/sys/class/leds/green:5g3pwr/brightness
/bin/sleep 3
echo 1 >/sys/class/leds/green:5g1pwr/brightness
/bin/sleep 3
echo 1 >/sys/class/leds/green:5g2pwr/brightness
/bin/sleep 3
echo 1 >/sys/class/leds/green:5g3pwr/brightnes
		exit 0
	EOF
fi

exit 0