#!/bin/sh
source /etc/os-release
if [ "$ID" = "openmptcprouter" ]; then
	cat > "/etc/opkg/customfeeds.conf" <<-EOF
	    src/gz openwrt_luci http://packages.openmptcprouter.com/${VERSION_ID}/${OPENWRT_ARCH}/luci
	    src/gz openwrt_packages http://packages.openmptcprouter.com/${VERSION_ID}/${OPENWRT_ARCH}/packages
	    src/gz openwrt_base http://packages.openmptcprouter.com/${VERSION_ID}/${OPENWRT_ARCH}/base
	    src/gz openwrt_routing http://packages.openmptcprouter.com/${VERSION_ID}/${OPENWRT_ARCH}/routing
	    src/gz openwrt_telephony http://packages.openmptcprouter.com/${VERSION_ID}/${OPENWRT_ARCH}/telephony
	EOF
	TARGET="$(cat /etc/banner | awk '/TARGET/ {print $2}')"
	cat > "/etc/opkg/distfeeds.conf" <<-EOF
	    src/gz openmptcprouter_core http://download.openmptcprouter.com/release/${VERSION_ID}/${TARGET}/targets/${OPENWRT_BOARD}/packages
	    src/gz openmptcprouter_base http://download.openmptcprouter.com/release/${VERSION_ID}/${TARGET}/packages/${OPENWRT_ARCH}/base
	    src/gz openmptcprouter_luci http://download.openmptcprouter.com/release/${VERSION_ID}/${TARGET}/packages/${OPENWRT_ARCH}/luci
	    src/gz openmptcprouter_openmptcprouter http://download.openmptcprouter.com/release/${VERSION_ID}/${TARGET}/packages/${OPENWRT_ARCH}/openmptcprouter
	    src/gz openmptcprouter_packages http://download.openmptcprouter.com/release/${VERSION_ID}/${TARGET}/packages/${OPENWRT_ARCH}/packages
	EOF
fi