#!/bin/sh

# Remove settings defined in /etc/sysctl.conf that are already defined in /etc/sysctl.d/
sed -i -e '/tcp_fin_timeout/d' -e '/tcp_keepalive_time/d' -e '/nf_conntrack_max/d' /etc/sysctl.conf
exit 0
