#!/bin/sh

cd /etc/uci-defaults || exit 0
source /etc/os-release

OMRVERSION=$(echo $VERSION | sed 's/v//')
uci -q set openmptcprouter.settings=settings
uci -q set openmptcprouter.settings.version=${OMRVERSION}
uci -q commit

exit 0
