#!/bin/sh /etc/rc.common
# Copyright (C) 2024 Ycarus (Yannick Chabanois) <ycarus@zugaina.org> for OpenMPTCProuter

START=99
STOP=8
USE_PROCD=1

PROG=/usr/lib/omr-bypass/ndpid-flows-tracker
FLOWS_DIR=/tmp/ndpid-flows

start_service() {
	[ ! -x /usr/sbin/ndpisrvd ] && return 0
	! pidof ndpisrvd >/dev/null 2>&1 && return 0

	mkdir -p "$FLOWS_DIR"

	procd_open_instance ndpid-flows-tracker
	procd_set_param command "$PROG"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/omr-bypass-ndpid-flows.pid
	procd_close_instance
}

stop_service() {
	rm -rf /tmp/ndpid-flows
	logger -t omr-bypass-ndpid-flows "Stopped"
}

service_triggers() {
	procd_add_reload_trigger "ndpid"
}
