#!/bin/sh
# Copyright (c) 2018 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.

PIPE_PATH="/var/run/hyd-map-cmd.fifo"
if [ -p $PIPE_PATH ] && [ -w $PIPE_PATH ]; then
    echo $* > $PIPE_PATH
fi
