#
# Copyright (C) 2018-2019 Ycarus (Yannick Chabanois) <ycarus@zugaina.org> for OpenMPTCProuter
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for DSVPN
LUCI_DEPENDS:=+dsvpn

PKG_LICENSE:=GPLv3

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
