#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.2.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'mptcp-bpf-dscp.service' >/dev/null || true
fi
# End automatically added section
