#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.ezengreen >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.ezengreen=/luci-static/ezengreen
		set luci.main.mediaurlbase=/luci-static/ezengreen
		commit luci
	EOF
fi

exit 0
