#!/bin/sh

if [ "$(uci -q get luci.themes.ezengreen)" = "" ]; then
	uci batch <<-EOF
		set luci.themes.ezengreen=/luci-static/ezengreen
		set luci.main.mediaurlbase=/luci-static/ezengreen
		commit luci
	EOF
fi
exit 0
