#!/bin/sh
if [ "$(uci -q show network.globals | grep mptcp_path_manager)" = "" ]; then
	uci -q batch <<-EOF
	set network.globals.multipath='enable'
	set network.globals.mptcp_path_manager='fullmesh'
	set network.globals.mptcp_scheduler='default'
	set network.globals.congestion='olia'
	set network.globals.mptcp_checksum=1
	set network.globals.mptcp_syn_retries=30
	commit network
	EOF
fi
if [ "$(uci -q get network.globals.mptcp_syn_retries)" = "4" ]; then
	uci -q batch <<-EOF
	set network.globals.mptcp_syn_retries=30
	commit network
	EOF
fi
if [ "$(uci -q get network.globals.mptcp_checksum)" = "enable" ]; then
	uci -q batch <<-EOF
	set network.globals.mptcp_checksum=1
	EOF
fi
if [ "$(uci -q get network.globals.mptcp_checksum)" = "disable" ]; then
	uci -q batch <<-EOF
	set network.globals.mptcp_checksum=0
	EOF
fi

if [ "$(uci -q show network.globals | grep mptcp_fullmesh)" = "" ]; then
	uci -q batch <<-EOF
	set network.globals.mptcp_fullmesh_num_subflows=1
	set network.globals.mptcp_fullmesh_create_on_err=1
	set network.globals.mptcp_ndiffports_num_subflows=1
	commit network
	EOF
fi
uci -q batch <<-EOF
    delete ucitrack.@mptcp[-1]
    add ucitrack mptcp
    set ucitrack.@mptcp[-1].init=mptcp
    add_list ucitrack.@network[-1].affects=mptcp
    commit ucitrack
EOF
exit 0