#!/bin/sh
uci -q batch <<-EOF
    set network.globals.mptcp_path_manager='fullmesh'
    set network.globals.mptcp_scheduler='default'
    set network.globals.congestion='olia'
    commit network
EOF
uci -q batch <<-EOF
    delete ucitrack.@mptcp[-1]
    add ucitrack mptcp
    set ucitrack.@mptcp[-1].init=mptcp
    add_list ucitrack.@network[-1].affects=mptcp
    commit ucitrack
EOF