#
# Copyright (C) 2018 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Quota configuration module
LUCI_DEPENDS:=+omr-quota

PKG_LICENSE:=Apache-2.0

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
