#
# Copyright (C) 2018 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Quota configuration module
LUCI_DEPENDS:=+omr-quota

PKG_LICENSE:=GPLv3

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
