#
# Copyright (C) 2018-2019 Ycarus (Yannick Chabanois) <ycarus@zugaina.org>
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Quota configuration module
LUCI_DEPENDS:=+omr-quota

PKG_LICENSE:=GPLv3

#include ../luci/luci.mk
include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
