#!/bin/sh
uci -q batch <<-EOF
    delete ucitrack.@omr-quota[-1]
    add ucitrack omr-quota
    set ucitrack.@omr-quota[-1].init="omr-quota"
    add_list ucitrack.@network[-1].affects="omr-quota"
    commit ucitrack
EOF