
#
# Copyright (C) 2018-2026 Ycarus (Yannick Chabanois) <ycarus@zugaina.org> for OpenMPTCProuter
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Interface Event History for OpenMPTCProuter
LUCI_DEPENDS:=+omr-events

PKG_LICENSE:=GPLv3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
